FROM centos:7.9.2009

# Install things we need to build or run.
# - Procstar's test setup uses `which` to find executables.
# - The Rust `native-tls` crate's `vendor` feature includes a vendored OpenSSL, which requires IPC::Cmd to build from source.
RUN yum group install "Development Tools" -y && \
    yum install which devtoolset-7 perl-IPC-Cmd -y && \
    yum clean all

ENV RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo
ENV PATH $CARGO_HOME/bin:/opt/rh/devtoolset-7/root/usr/bin:$PATH

# Install Rustup and Rust.
RUN mkdir -p "$CARGO_HOME" && mkdir -p "$RUSTUP_HOME" && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable && \
    chmod -R a=rwX $CARGO_HOME

# Install Miniconda.
RUN curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -sSf -o miniconda.sh && \
    bash ./miniconda.sh -b -u -p /conda && \
    rm miniconda.sh && \
    /conda/bin/conda install conda-build -y

ENV PATH /conda/bin:$PATH

WORKDIR /source
