name: PR Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache: true

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true

    - name: Run Rust tests
      run: cargo test

    - name: Check Rust formatting  
      run: cargo fmt --all -- --check

    - uses: PyO3/maturin-action@v1
      with:
        command: build
        args: --find-interpreter
        container: off
        sccache: true

    - name: Run Python tests
      run: uv run pytest
