name: PR Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache: true

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true

    - name: Run Rust tests
      run: cargo test

    - name: Run clippy linting
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Check Rust formatting  
      run: cargo fmt --all -- --check

    - name: Install procstar
      # use dev profile to share cache with cargo test
      run: uv sync -v --config-settings="build-args=--profile=dev"

    - name: Run Python tests
      run: uv run pytest
