name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Type of release'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache: true

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true

    - name: Bump version
      id: bump
      run: |
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
        git config -l

        echo "previous-version=$(uvx bump-my-version show current_version)" | tee -a $GITHUB_OUTPUT

        uvx bump-my-version bump --allow-dirty ${{ inputs.release-type }}

        ([[ $? -gt 0 ]] && echo "bumped=false" || echo "bumped=true") | tee -a $GITHUB_OUTPUT
        echo "current-version=$(uvx bump-my-version show current_version)" | tee -a $GITHUB_OUTPUT
        echo "git-tag=v$(uvx bump-my-version show current_version)" | tee -a $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ github.token }}

    - uses: PyO3/maturin-action@v1
      with:
        command: build
        sccache: true
        manylinux: auto
        container: quay.io/pypa/manylinux_2_28_x86_64:latest
        before-script-linux: |
          dnf install -y perl-IPC-Cmd
        args: --release

    - name: Create pypi-index directory
      if: steps.bump.outputs.bumped == 'true'
      run: |
        mkdir -p pypi-index
        cp target/wheels/*.whl pypi-index/

    - name: Generate PyPI index with dumb-pypi
      if: steps.bump.outputs.bumped == 'true'
      run: |
        uvx dumb-pypi --package-list <(cd ./pypi-index && ls *.whl) --output-dir pypi-index --packages-url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/

    - name: Setup Pages
      if: steps.bump.outputs.bumped == 'true'
      uses: actions/configure-pages@v5

    - name: Upload Pages artifact
      if: steps.bump.outputs.bumped == 'true'
      uses: actions/upload-pages-artifact@v3
      with:
        path: pypi-index

    - name: Deploy to Github Pages
      if: steps.bump.outputs.bumped == 'true'
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Commit pypi-index to repository
      if: steps.bump.outputs.bumped == 'true'
      run: |
        git add pypi-index
        git commit -m "Add PyPI index for ${{ steps.bump.outputs.git-tag }}"
        git push origin HEAD:${{ github.ref }}

    - name: Push bumped version
      if: steps.bump.outputs.bumped == 'true'
      run: |
        git push origin HEAD:${{ github.ref }}
        git push origin ${{ steps.bump.outputs.git-tag }}

    - name: Create Github release
      if: steps.bump.outputs.bumped == 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.bump.outputs.git-tag }}
        name: ${{ steps.bump.outputs.git-tag }}
        files: |
          target/wheels/*.whl
        draft: false
        prerelease: false
        generate_release_notes: true
